/*
 * ParserSLRAboutBox.java
 */

package VUE;

import MOTEUR.*;
import MOTEUR.TableAnalyse;
import java.awt.Color;
import java.util.ArrayList;
import org.jdesktop.application.Action;


public class VueAnalyseMot extends javax.swing.JDialog {

    public VueAnalyseMot(java.awt.Frame parent) {
        super(parent);
        
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        setTitle("Analyser un mot");
    }

    @Action public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(VUE.Main.class).getContext().getResourceMap(VueAnalyseMot.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(VUE.Main.class).getContext().getActionMap(VueAnalyseMot.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setToolTipText(resourceMap.getString("jButton2.toolTipText")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setAction(actionMap.get("analyser")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jButton3.setAction(actionMap.get("tableAnalyse")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(86, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void analyser() {
        //if(!jTextField1.getText().equals("")){
            System.out.println("-----------------------------------");
        jTextArea1.setForeground(Color.black);
        jTextArea1.setText("DEBUT DE L'ANALYSE");
        String pileEntree=jTextField1.getText();
        String txt=pileEntree;
        ArrayList<String> etat=new ArrayList();
        ArrayList<String> flot=new ArrayList();
        ArrayList<String> stick=new ArrayList();

        char c=' ';
        boolean bo=false;
        Grammaire gr=Grammaire.getInstance();
        pileEntree=pileEntree+"$";
        for(int i=0;i<pileEntree.length();i++){
           c=pileEntree.charAt(i);
           if(!gr.testTenminaux(c)){
           bo=true;
           break;
           }
        }
        
        if(bo){
            pileEntree=pileEntree.replaceFirst(c+""," >"+c+"< ");
            jTextArea1.setText(jTextArea1.getText()+"\n"+"erreur dans le mot à analyser \n " +
                    "le caractère '"+c+"' ne fait pas partie de nos Terminaux \n" +
                    "Mot : " + pileEntree+ "\n"+
                    "Echec dans l'analyse du mot");
            jTextArea1.setForeground(Color.red);
            return;
        }
        etat.add("0");
        //pileEntree=pileEntree+"$";
        char caractereCourant=' ';
        String action;
        jTextArea1.setText("");
        boolean accepte=false;
        while(pileEntree.length()>0){
            caractereCourant=pileEntree.charAt(0);
            //jTextArea1.setText(jTextArea1.getText()+caractereCourant);
            action=null;
        
            //*
            if(etat.size()>0){
            if(TableAnalyse.getInstance().getAction()[Integer.parseInt(etat.get(etat.size()-1))][gr.getTerminaux().indexOf(caractereCourant+"")].size()>0)
            {

                action=TableAnalyse.getInstance().getAction()[Integer.parseInt(etat.get(etat.size()-1))][gr.getTerminaux().indexOf(caractereCourant+"")].get(0);
            //jTextArea1.setText(jTextArea1.getText()+action+"e");
                System.out.println(action);
                if((action.charAt(0)+"").equals("d")){
                    pileEntree=pileEntree.substring(1,pileEntree.length());
                    String go=action.substring(1,action.length());
                    etat.add(go);
                    

                }else if((action.charAt(0)+"").equals("r")){
                    String go=action.substring(1,action.length());
                    flot.add(go);
                    Regle rg=Regle.getRegleNum(Integer.parseInt(go));
                    int kp=rg.getDroite()[0].length();
                    if(rg.getDroite()[0].equals(FristSuiv.vide))
                        kp=0;
                    rg.afficher();

                    for(int kpt=0;kpt<kp;kpt++){
                        etat.remove(etat.size()-1);
                    }
                    if(etat.size()==0){
                      System.out.println("erreur dans pile d'etat");
                    jTextArea1.setForeground(Color.red);
                    jTextArea1.setText(jTextArea1.getText()+"\n"+"" +
                            "ERREUR DE TYPE 5"+
                            "\n"+"Nous avons decelé une problème lors de l'analyse");
                    break;
                        
                    }
                    System.out.println(kp+"--"+etat.get(etat.size()-1));
                    action=TableAnalyse.getInstance().getSuccesseur()[Integer.parseInt(etat.get(etat.size()-1))][Grammaire.getInstance().getNonTerminaux().replaceAll("Z","").indexOf("" + rg.getGauche())]+"";
                    if(!action.equals("null")){
                    etat.add(action);
                    }
                    else{
                    System.out.println("erreur dans etat");
                    jTextArea1.setForeground(Color.red);
                    jTextArea1.setText(jTextArea1.getText()+"\n"+"" +
                            "ERREUR DE TYPE 1"+
                            "\n"+"Nous avons decelé une problème lors de l'analyse" +
                            "\n explications" +
                            "\n il nous reste à analyser "+pileEntree+
                            "\n mais aucune action n'a été definie pour le caractère "+pileEntree.charAt(0)+
                            " \n Etat "+etat.get(etat.size()-1));
                    break;
                    }

                }else if((action.charAt(0)+"").equals("a")){
                    accepte=true;
                    break;
                }else{
                    jTextArea1.setForeground(Color.red);
                   jTextArea1.setText(jTextArea1.getText()+"\n"+"" +
                            "ERREUR DE TYPE 3"+
                            "\n"+"Nous avons decelé une problème lors de l'analyse" +
                            "\n explications" +
                            "\n cette erreur est indefini : reste du mot à analyser "+pileEntree+
                            "\n caractère en analyse"+pileEntree.charAt(0)+
                            "\n" +"etat : "+etat.get(etat.size()-1));
                break;
                }
            }else{
                jTextArea1.setForeground(Color.red);
                 jTextArea1.setText(jTextArea1.getText()+"\n"+"" +
                            "ERREUR DE TYPE 2"+
                            "\n"+"Nous avons decelé une problème lors de l'analyse" +
                            "\n explications" +
                            "\n il nous reste à analyser "+pileEntree+
                            "\n mais aucune action n'a été definie pour le caractère "+pileEntree.charAt(0)+
                            " \n Etat "+etat.get(etat.size()-1));

                 break;
            }
        }else{
            System.out.println("erreur d'etat null");
            jTextArea1.setText(jTextArea1.getText()+"\n"+"" +
                            "ERREUR DE TYPE 4"+
                            "\n"+"Nous avons decelé une problème lors de l'analyse" +
                            "\n explications" +
                            "\n il nous reste à analyser "+pileEntree+
                            "\n mais il n'ya plus d'états"+
                            " \n Etat");
            }


           
            // */
        }
        if(accepte){
         jTextArea1.setForeground(Color.GREEN);
        jTextArea1.setText("ANALYSE COMPLETE \n" +
                "Le mot '"+txt+"' a été analysé et accepté");

        }


        //}
    }

    @Action
    public void tableAnalyse() {
         Object[][] row=new Object[Item.getcollection().size()][Grammaire.getInstance().getNonTerminaux().length()+Grammaire.getInstance().getTerminaux().length()+1];
        char[] name1=(Grammaire.getInstance().getTerminaux()+Grammaire.getInstance().getNonTerminaux()).toCharArray();
        Object[] name=new Object[name1.length+1];
        name[0]="ETATS";
        for(int i=0;i<name1.length;i++){
            name[i+1]=name1[i];
        }
        for(int i=0;i<Item.getcollection().size();i++){
            row[i][0]=i;
            for(int j=0;j<name1.length;j++){
                if(j<Grammaire.getInstance().getTerminaux().length()){
                    String txt=TableAnalyse.getInstance().Action[i][j].toString();
                    txt=txt.replace("[","");
                    txt=txt.replace("]","");
                    row[i][j+1]=txt;


                }else{
                String txt=TableAnalyse.getInstance().successeur[i][j-Grammaire.getInstance().getTerminaux().length()]+"";
                row[i][j+1]=txt.replaceAll("null","");

                }
            }
    }
         new VueTableAnalyse(null,true,row,name).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
